### ISSUE TITLE
Upload photo

### ISSUE THREAD

**Issue by rhatami7495** [brunocvcunha/instagram4j#407] opened 2020-01-15 06:08 UTC
Upload a photo to your feed not working!!!!

**Comment by Aulig** [comment] 2020-01-15 18:40
This issue is not very helpful as it lacks any information that could help while fixing. Also it's probably a duplicate of #393

**Comment by Kanaris** [comment] 2020-01-23 23:08
The same as 
https://github.com/brunocvcunha/instagram4j/issues/393

**Closed** 2020-01-25 10:48 UTC
